#information for the role to be assumed by github
accountId: 782042535526
githubRole: github-role
clusterRole: OrganizationAccountAccessRole
assetBucket: infra-common-assets-bmo-lab
region: ca-central-1